fit adjustments
pymc-labs/pymc-marketing pull request #365
Opened 2023-08-19 12:17 UTC by michaelraczycki

This PR contains the following changes:

sample_model():
    - **kwargs are getting passed now to all sampling functions, instead of just to pm.sample()
    - sample_prior_predictive and sample_posterior_predictive are by default not triggered
    - new parameters : prior_predictive: bool 
                                     posterior_predictive: bool
      that control whether the corresponding distributions get sampled.
mypy fixes
docstrings updates and changes

2023-08-20 13:21 UTC, michaelraczycki commented
@ricardoV94 , @juanitorduz please let me know what you think about it, I think it might be first step on improving the time length our tests take to finish

2023-08-21 09:49 UTC, michaelraczycki commented
merging this should close #364

2023-08-21 13:20 UTC, juanitorduz approved these changes

2023-08-21 13:22 UTC, juanitorduz commented
> @ricardoV94 , @juanitorduz please let me know what you think about it, I think it might be first step on improving the time length our tests take to finish

Thanks! This was definitely needed! I still wanna avoid sampling for the plot tests :)

2023-08-21 13:30 UTC, ricardoV94 requested changes

2023-08-21 13:45 UTC, michaelraczycki commented on pymc_marketing/model_builder.py
> +                    )
could you suggest some other form?

2023-08-22 06:40 UTC, ricardoV94 commented on pymc_marketing/model_builder.py
> +                    )
posterior_predictive_kwargs

2023-08-22 06:42 UTC, ricardoV94 commented on pymc_marketing/model_builder.py
> +                    )
Also rename **kwargs internally to **sample_kwargs, so it's easier to read where those go

2023-08-22 06:43 UTC, ricardoV94 commented on pymc_marketing/model_builder.py
> +        posterior_predictive = kwargs.pop("posterior_predictive", False)
These should be explicit arguments, and not hidden inside kwargs

2023-08-22 06:45 UTC, ricardoV94 commented on pymc_marketing/model_builder.py
> +                if prior_kwargs is not None:
Nitpick: I would create an empty dict, so the same call to `pm.sample_prior_predictive` can be done without repeating code

2023-08-22 06:46 UTC, ricardoV94 commented on tests/model_builder/test_model_builder.py
> +@pytest.mark.slow
Just reduce tune and draws, specially since nothing is being checked other than the trace exists after the fact

2023-09-01 07:53 UTC, ricardoV94 approved these changes

2023-09-01 08:20 UTC, merged