New spends forward pass
pymc-labs/pymc-marketing pull request #456
Opened 2023-12-07 06:51 UTC by wd60622

Current code for #451

2023-12-07 19:26 UTC, wd60622 commented
Got the prior functionality working

<img width="1003" alt="prior-and-posterior-support" src="https://github.com/pymc-labs/pymc-marketing/assets/57733339/811c2ec5-735e-4336-9e18-5d59e58de999">

The inverse_transform could be used if the model was fit. Might be good to toggle inverse_transform even for the posterior. Any thoughts here?

2024-01-12 03:25 UTC, wd60622 commented
Will add the transformation back to original space and continue with this PR after #482

2024-01-27 20:00 UTC, wd60622 commented
Think that the API is finalized 
Will add to the docstrings and will add some tests tomorrow and work through any rebase issues

2024-02-05 06:15 UTC, twiecki commented
What's the status of this? Any blockers to moving this forward?

2024-02-05 07:27 UTC, wd60622 commented
> What's the status of this? Any blockers to moving this forward?

Have the main functionality built out
Next steps

- add method docstring for plotting
- round out test for non-plotting method
- review & feedback

2024-02-06 17:03 UTC, wd60622 commented
I'd appreciate any feedback on improving the `new_spend_contributions` function
I brought in `pytest-mpl` in order to test `plot_new_spend_contributions` but I think if `new_spend_contributions` is tested enough, it might be fine at the moment

Would love to hear any thoughts and feedback

2024-02-09 13:07 UTC, juanitorduz requested changes
This looks very nice! I added some minor suggestions on the docstrings to clarify this better for the end-user. WDYT?

2024-02-09 13:19 UTC, wd60622 commented on pymc_marketing/mmm/delayed_saturated_mmm.py
> +            beta_channel = pm.HalfFlat("beta_channel", dims=("channel",))
The are arbitrary and could all be Flat distributions. Only the shape is required to match in order to work with the `sample_posterior_predictive` method

2024-02-09 13:19 UTC, wd60622 commented on pymc_marketing/mmm/delayed_saturated_mmm.py
> +            level=["weeks_since_spend", "channel"]
"time units since spend"? 😆

2024-02-09 13:20 UTC, wd60622 commented on pymc_marketing/mmm/delayed_saturated_mmm.py
> +        )
Good call. Will do!

2024-02-11 17:05 UTC, wd60622 commented
I've addressed all the feedback, @juanitorduz
Thanks!

I've separated out the "new_spend" creation into a function and added some more to the docstrings so hopefully that brings in some clarity. 

Let me know what you think!

2024-02-11 17:07 UTC, wd60622 commented on pymc_marketing/mmm/delayed_saturated_mmm.py
> +            beta_channel = pm.HalfFlat("beta_channel", dims=("channel",))
Might be good to get the dims from the config though...

2024-02-15 19:25 UTC, juanitorduz commented
@wd60622 looks great! There is one test failing though. If you fix it we can merge this one  :)

2024-02-16 06:50 UTC, wd60622 commented
Have the test passing locally but not in the action 😢  

Running the action with 3.11 with the latest pymc to see if the pymc version has an impact. The test depends on the sample_prior_predictive method. Not sure if that has changed

Might just mock the idata for all of these tests with the plots and hope giving a seed will keep the results the sample

2024-03-06 17:52 UTC, wd60622 commented
Trying to mock the prior in the `model.idata` 
Hope that that works. If not, I will pull out the plotting into a function and tests on some fixed data. 

If all else fails, these are tests against the plotting images and can maybe be omitted. Thoughts? @juanitorduz @ricardoV94

2024-03-08 14:20 UTC, juanitorduz commented
@wd60622 I am getting the same error as in https://github.com/matplotlib/pytest-mpl/issues/69 . Can you please add `markers =["mpl_image_compare"]` to pyproject.toml as in

```
[tool.pytest.ini_options]
addopts = [
    "-v",
    "--strict-markers",
    "--strict-config",
    "--cov=pymc_marketing",
    "--cov-report=term-missing",
    "--color=yes",
]
markers =["mpl_image_compare"]
filterwarnings = ["ignore::DeprecationWarning:bokeh.core.property.primitive:37"]
testpaths = "tests"
```

2024-03-08 14:59 UTC, wd60622 commented
Failed again even after using fresh environment 😢 
Would you be able to check one more time @juanitorduz

2024-03-08 15:05 UTC, juanitorduz commented
> Failed again even after using fresh environment 😢 Would you be able to check one more time @juanitorduz

I suggest we make sure the plot runs (as other plots tests) and create an issue to add this matplotlib testing framework. I would not delay this feature because of this :)

2024-03-08 15:18 UTC, wd60622 commented
> > Failed again even after using fresh environment 😢 Would you be able to check one more time @juanitorduz
> 
> I suggest we make sure the plot runs (as other plots tests) and create an issue to add this matplotlib testing framework. I would not delay this feature because of this :)

Sounds great!

2024-03-08 19:38 UTC, juanitorduz approved these changes

2024-03-08 20:19 UTC, merged

2024-03-08 20:19 UTC, juanitorduz commented
Thanks @wd60622 !

2024-03-08 20:35 UTC, wd60622 commented
> Thanks @wd60622 !

Thank you for the review!