Remove warnings during tests
pymc-labs/pymc-marketing pull request #823
Opened 2024-07-09 15:24 UTC by wd60622

## Description

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-07-09 15:47 UTC, wd60622 commented
WIP. The more the merrier

2024-07-09 20:17 UTC, juanitorduz commented
Great 🙌

2024-07-10 17:26 UTC, wd60622 commented
Only 7 warnings on the 3.10 tests now. Mainly from the CLV fits with potentials
Any thoughts on this? 
https://github.com/pymc-labs/pymc-marketing/actions/runs/9876739390/job/27276622994

2024-07-10 17:26 UTC, wd60622 commented
Bunch of warnings from pytest deprecations upcoming in python 3.14...

2024-07-10 18:49 UTC, juanitorduz requested changes
LGTM. Just a suggestion about the docs :)

2024-07-10 18:49 UTC, juanitorduz commented on pymc_marketing/mmm/delayed_saturated_mmm.py
> +        ),
If we have a default of `None` we must ensure in the docstrings and the Field description what is the max lag used. From what I see below is `10` but this has to be explicit for the user in the docs :)

2024-07-11 12:01 UTC, juanitorduz approved these changes

2024-07-11 12:01 UTC, merged