Update docs in transformers.py
pymc-labs/pymc-marketing pull request #864
Opened 2024-07-24 10:38 UTC by ferrine

docs: Fix the docstring

## Description

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-07-24 10:53 UTC, wd60622 commented
The example plot has before marked as the default. Can you change that as well

2024-07-24 10:53 UTC, wd60622 requested changes
Good catch. Request for the legend in plots

2024-07-29 19:13 UTC, juanitorduz approved these changes

2024-07-29 19:31 UTC, wd60622 approved these changes

2024-07-29 19:31 UTC, merged

2024-07-29 19:31 UTC, wd60622 commented
Good catch @ferrine !